<?php

/**
 * user_detailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class user_detailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object user_detailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('user_details');
    }
}