<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/05 22:55:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
